DATASETS:
  NAME: "CIFAR100"
  # SEED: 42 (unused)
  CIFAR:
    SHUFFLE_INDICES: False
    TRAIN_INDICES: [0, 45000,]
    VALID_INDICES: [45000, 50000,]
    DATA_AUGMENTATION: "STANDARD_TRAIN_TRANSFORM"

DATALOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: False

MODEL:
  META_ARCHITECTURE:
    NAME: "ClassificationModelBase"
  PIXEL_MEAN: [0.5072, 0.4866, 0.4410,]
  PIXEL_STD: [0.2673, 0.2564, 0.2760,]
  BACKBONE:
    NAME: "build_preresnet_backbone"
    RESNET:
      CHANNELS: 3
      IN_PLANES: 16
      FIRST_BLOCK:
        USE_NORM_LAYER: False
        USE_ACTIVATION: False
        USE_POOL_LAYER: False
        CONV_KSP: [3, 1, 1,]
        # POOL_KSP: [3, 2, 1,] (unused)
      BLOCK: "BasicBlock"
      SHORTCUT: "ProjectionShortcut"
      NUM_BLOCKS: [4, 4, 4,]
      WIDEN_FACTOR: 10
      CONV_LAYERS: "Conv2d"
      NORM_LAYERS: "BatchNorm2d"
      ACTIVATIONS: "ReLU"
  CLASSIFIER:
    NAME: "build_softmax_classifier"
    SOFTMAX_CLASSIFIER:
      FEATURE_DIM: 640
      NUM_CLASSES: 100
      NUM_HEADS: 1
      USE_BIAS: True
      LINEAR_LAYERS: "Linear"

SOLVER:
  NUM_EPOCHS: 300
  BATCH_SIZE: 256
  VALID_FREQUENCY: 30
  VALID_FINALE: 30
  OPTIMIZER:
    NAME: "SGD"
    SGD:
      BASE_LR: 0.2
      WEIGHT_DECAY: 0.0005
      MOMENTUM: 0.9
      NESTEROV: False
  SCHEDULER:
    NAME: "WarmupLinearDecayLR"
    WARMUP_LINEAR_DECAY_LR:
      MILESTONES: [5, 150, 270,]
      WARMUP_METHOD: "linear"
      WARMUP_FACTOR: 0.01
      GAMMA: 0.01

NUM_GPUS: 4
CUDNN_BENCHMARK: False
CUDNN_DETERMINISTIC: False
SEED: -1
OUTPUT_DIR: "./outputs/C100_WRN28x10_SGD/"
