MODEL:
  BATCH_ENSEMBLE:
    ENABLED: True
    ENSEMBLE_SIZE: 120
    USE_ENSEMBLE_BIAS: True
    ALPHA_INITIALIZER:
      NAME: "normal"
      VALUES: [1.0, 0.5,]
    GAMMA_INITIALIZER:
      NAME: "normal"
      VALUES: [1.0, 0.5,]
  META_ARCHITECTURE:
    NAME: "ClassificationModelBase"
  PIXEL_MEAN: [0.5072, 0.4866, 0.4410,]
  PIXEL_STD: [0.2673, 0.2564, 0.2760,]
  BACKBONE:
    NAME: "build_resnet_backbone"
    RESNET:
      CHANNELS: 3
      IN_PLANES: 16
      FIRST_BLOCK:
        USE_NORM_LAYER: False
        USE_ACTIVATION: False
        USE_POOL_LAYER: False
        CONV_KSP: [3, 1, 1,]
        # POOL_KSP: [3, 2, 1,] (unused)
      BLOCK: "BasicBlock"
      SHORTCUT: "IdShortcut"
      NUM_BLOCKS: [2, 2, 2, 2]
      WIDEN_FACTOR: 10
      CONV_LAYERS: "Conv2d_BatchEnsemble"
      NORM_LAYERS: "BatchNorm2d"
      ACTIVATIONS: "ReLU"
  CLASSIFIER:
    NAME: "build_softmax_classifier"
    SOFTMAX_CLASSIFIER:
      FEATURE_DIM: 640
      NUM_CLASSES: 100
      NUM_HEADS: 1
      USE_BIAS: True
      LINEAR_LAYERS: "Linear_BatchEnsemble"

SOLVER:
  NUM_EPOCHS: 300
  BATCH_SIZE: 64
  VALID_FREQUENCY: 30
  VALID_FINALE: 30
  OPTIMIZER:
    NAME: "SGD"
    SGD:
      BASE_LR: 0.05
      BASE_LR_BE: 0.025
      WEIGHT_DECAY: 0.0005
      WEIGHT_DECAY_BE: 0.0000
      MOMENTUM: 0.9
      MOMENTUM_BE: 0.9
      NESTEROV: False
      NESTEROV_BE: False
  SCHEDULER:
    NAME: "WarmupLinearDecayLR"
    WARMUP_LINEAR_DECAY_LR:
      MILESTONES: [5, 150, 270,]
      WARMUP_METHOD: "linear"
      WARMUP_FACTOR: 0.01
      GAMMA: 0.01

NUM_GPUS: 1
CUDNN_BENCHMARK: False
CUDNN_DETERMINISTIC: False
SEED: -1
OUTPUT_DIR: "stl10/outputs/"
